# Generated by Django 3.1.6 on 2021-03-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210317_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='continent_code',
            new_name='code',
        ),
    ]
