# Generated by Django 3.1.6 on 2021-03-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210317_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='follow',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='like',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='likecomment',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
