# Generated by Django 3.1.6 on 2021-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210317_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moto',
            field=models.TextField(null=True),
        ),
    ]
