# Generated by Django 3.1.6 on 2021-03-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210317_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='countrycode',
            new_name='code',
        ),
    ]
