# Generated by Django 3.1.6 on 2021-03-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_user_moto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='moto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
