# Generated by Django 3.1.7 on 2021-04-14 15:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210321_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('seen', models.BooleanField(default=False)),
                ('mentioned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_post_mentioned', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_post_mentioned', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='network.post')),
            ],
        ),
        migrations.CreateModel(
            name='CommentMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('seen', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='network.comment')),
                ('mentioned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_comment_mentioned', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_comment_mentioned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
