# Generated by Django 3.1.7 on 2021-04-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='kind',
            field=models.CharField(choices=[('like', 'Liked'), ('sad', 'Sad'), ('dislike', 'Disliked'), ('haha', 'Haha'), ('liquid', 'Liquid')], default='like', max_length=15),
        ),
    ]
