# Generated by Django 3.1.7 on 2021-04-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_like_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='kind',
            field=models.CharField(choices=[('like', 'like'), ('sad', 'sad'), ('dislike', 'dislike'), ('haha', 'haha'), ('liquid', 'liquid')], default='like', max_length=15),
        ),
    ]
