# Generated by Django 3.1.7 on 2021-04-28 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20210427_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
