import os,django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project4.settings")
django.setup()

from network.models import*
  
country = Country(title='Afghanistan', code='AF')
country.save() 
country = Country(title='Åland Islands', code='AX')
country.save() 
country = Country(title='Albania', code='AL')
country.save() 
country = Country(title='Algeria', code='DZ')
country.save() 
country = Country(title='American Samoa', code='AS')
country.save() 
country = Country(title='AndorrA', code='AD')
country.save() 
country = Country(title='Angola', code='AO')
country.save() 
country = Country(title='Anguilla', code='AI')
country.save() 
country = Country(title='Antarctica', code='AQ')
country.save() 
country = Country(title='Antigua and Barbuda', code='AG')
country.save() 
country = Country(title='Argentina', code='AR')
country.save() 
country = Country(title='Armenia', code='AM')
country.save() 
country = Country(title='Aruba', code='AW')
country.save() 
country = Country(title='Australia', code='AU')
country.save() 
country = Country(title='Austria', code='AT')
country.save() 
country = Country(title='Azerbaijan', code='AZ')
country.save() 
country = Country(title='Bahamas', code='BS')
country.save() 
country = Country(title='Bahrain', code='BH')
country.save() 
country = Country(title='Bangladesh', code='BD')
country.save() 
country = Country(title='Barbados', code='BB')
country.save() 
country = Country(title='Belarus', code='BY')
country.save() 
country = Country(title='Belgium', code='BE')
country.save() 
country = Country(title='Belize', code='BZ')
country.save() 
country = Country(title='Benin', code='BJ')
country.save() 
country = Country(title='Bermuda', code='BM')
country.save() 
country = Country(title='Bhutan', code='BT')
country.save() 
country = Country(title='Bolivia', code='BO')
country.save() 
country = Country(title='Bosnia and Herzegovina', code='BA')
country.save() 
country = Country(title='Botswana', code='BW')
country.save() 
country = Country(title='Bouvet Island', code='BV')
country.save() 
country = Country(title='Brazil', code='BR')
country.save() 
country = Country(title='British Indian Ocean Territory', code='IO')
country.save() 
country = Country(title='Brunei Darussalam', code='BN')
country.save() 
country = Country(title='Bulgaria', code='BG')
country.save() 
country = Country(title='Burkina Faso', code='BF')
country.save() 
country = Country(title='Burundi', code='BI')
country.save() 
country = Country(title='Cambodia', code='KH')
country.save() 
country = Country(title='Cameroon', code='CM')
country.save() 
country = Country(title='Canada', code='CA')
country.save() 
country = Country(title='Cape Verde', code='CV')
country.save() 
country = Country(title='Cayman Islands', code='KY')
country.save() 
country = Country(title='Central African Republic', code='CF')
country.save() 
country = Country(title='Chad', code='TD')
country.save() 
country = Country(title='Chile', code='CL')
country.save() 
country = Country(title='China', code='CN')
country.save() 
country = Country(title='Christmas Island', code='CX')
country.save() 
country = Country(title='Cocos (Keeling) Islands', code='CC')
country.save() 
country = Country(title='Colombia', code='CO')
country.save() 
country = Country(title='Comoros', code='KM')
country.save() 
country = Country(title='Congo', code='CG')
country.save() 
country = Country(title='Congo, The Democratic Republic of the', code='CD')
country.save() 
country = Country(title='Cook Islands', code='CK')
country.save() 
country = Country(title='Costa Rica', code='CR')
country.save() 
country = Country(title='Cote D\'Ivoire', code='CI')
country.save() 
country = Country(title='Croatia', code='HR')
country.save() 
country = Country(title='Cuba', code='CU')
country.save() 
country = Country(title='Cyprus', code='CY')
country.save() 
country = Country(title='Czech Republic', code='CZ')
country.save() 
country = Country(title='Denmark', code='DK')
country.save() 
country = Country(title='Djibouti', code='DJ')
country.save() 
country = Country(title='Dominica', code='DM')
country.save() 
country = Country(title='Dominican Republic', code='DO')
country.save() 
country = Country(title='Ecuador', code='EC')
country.save() 
country = Country(title='Egypt', code='EG')
country.save() 
country = Country(title='El Salvador', code='SV')
country.save() 
country = Country(title='Equatorial Guinea', code='GQ')
country.save() 
country = Country(title='Eritrea', code='ER')
country.save() 
country = Country(title='Estonia', code='EE')
country.save() 
country = Country(title='Ethiopia', code='ET')
country.save() 
country = Country(title='Falkland Islands (Malvinas)', code='FK')
country.save() 
country = Country(title='Faroe Islands', code='FO')
country.save() 
country = Country(title='Fiji', code='FJ')
country.save() 
country = Country(title='Finland', code='FI')
country.save() 
country = Country(title='France', code='FR')
country.save() 
country = Country(title='French Guiana', code='GF')
country.save() 
country = Country(title='French Polynesia', code='PF')
country.save() 
country = Country(title='French Southern Territories', code='TF')
country.save() 
country = Country(title='Gabon', code='GA')
country.save() 
country = Country(title='Gambia', code='GM')
country.save() 
country = Country(title='Georgia', code='GE')
country.save() 
country = Country(title='Germany', code='DE')
country.save() 
country = Country(title='Ghana', code='GH')
country.save() 
country = Country(title='Gibraltar', code='GI')
country.save() 
country = Country(title='Greece', code='GR')
country.save() 
country = Country(title='Greenland', code='GL')
country.save() 
country = Country(title='Grenada', code='GD')
country.save() 
country = Country(title='Guadeloupe', code='GP')
country.save() 
country = Country(title='Guam', code='GU')
country.save() 
country = Country(title='Guatemala', code='GT')
country.save() 
country = Country(title='Guernsey', code='GG')
country.save() 
country = Country(title='Guinea', code='GN')
country.save() 
country = Country(title='Guinea-Bissau', code='GW')
country.save() 
country = Country(title='Guyana', code='GY')
country.save() 
country = Country(title='Haiti', code='HT')
country.save() 
country = Country(title='Heard Island and Mcdonald Islands', code='HM')
country.save() 
country = Country(title='Holy See (Vatican City State)', code='VA')
country.save() 
country = Country(title='Honduras', code='HN')
country.save() 
country = Country(title='Hong Kong', code='HK')
country.save() 
country = Country(title='Hungary', code='HU')
country.save() 
country = Country(title='Iceland', code='IS')
country.save() 
country = Country(title='India', code='IN')
country.save() 
country = Country(title='Indonesia', code='ID')
country.save() 
country = Country(title='Iran, Islamic Republic Of', code='IR')
country.save() 
country = Country(title='Iraq', code='IQ')
country.save() 
country = Country(title='Ireland', code='IE')
country.save() 
country = Country(title='Isle of Man', code='IM')
country.save() 
country = Country(title='Israel', code='IL')
country.save() 
country = Country(title='Italy', code='IT')
country.save() 
country = Country(title='Jamaica', code='JM')
country.save() 
country = Country(title='Japan', code='JP')
country.save() 
country = Country(title='Jersey', code='JE')
country.save() 
country = Country(title='Jordan', code='JO')
country.save() 
country = Country(title='Kazakhstan', code='KZ')
country.save() 
country = Country(title='Kenya', code='KE')
country.save() 
country = Country(title='Kiribati', code='KI')
country.save() 
country = Country(title='Korea, Democratic People\'S Republic of', code='KP')
country.save() 
country = Country(title='Korea, Republic of', code='KR')
country.save() 
country = Country(title='Kuwait', code='KW')
country.save() 
country = Country(title='Kyrgyzstan', code='KG')
country.save() 
country = Country(title='Lao People\'S Democratic Republic', code='LA')
country.save() 
country = Country(title='Latvia', code='LV')
country.save() 
country = Country(title='Lebanon', code='LB')
country.save() 
country = Country(title='Lesotho', code='LS')
country.save() 
country = Country(title='Liberia', code='LR')
country.save() 
country = Country(title='Libyan Arab Jamahiriya', code='LY')
country.save() 
country = Country(title='Liechtenstein', code='LI')
country.save() 
country = Country(title='Lithuania', code='LT')
country.save() 
country = Country(title='Luxembourg', code='LU')
country.save() 
country = Country(title='Macao', code='MO')
country.save() 
country = Country(title='Macedonia, The Former Yugoslav Republic of', code='MK')
country.save() 
country = Country(title='Madagascar', code='MG')
country.save() 
country = Country(title='Malawi', code='MW')
country.save() 
country = Country(title='Malaysia', code='MY')
country.save() 
country = Country(title='Maldives', code='MV')
country.save() 
country = Country(title='Mali', code='ML')
country.save() 
country = Country(title='Malta', code='MT')
country.save() 
country = Country(title='Marshall Islands', code='MH')
country.save() 
country = Country(title='Martinique', code='MQ')
country.save() 
country = Country(title='Mauritania', code='MR')
country.save() 
country = Country(title='Mauritius', code='MU')
country.save() 
country = Country(title='Mayotte', code='YT')
country.save() 
country = Country(title='Mexico', code='MX')
country.save() 
country = Country(title='Micronesia, Federated States of', code='FM')
country.save() 
country = Country(title='Moldova, Republic of', code='MD')
country.save() 
country = Country(title='Monaco', code='MC')
country.save() 
country = Country(title='Mongolia', code='MN')
country.save() 
country = Country(title='Montserrat', code='MS')
country.save() 
country = Country(title='Morocco', code='MA')
country.save() 
country = Country(title='Mozambique', code='MZ')
country.save() 
country = Country(title='Myanmar', code='MM')
country.save() 
country = Country(title='Namibia', code='NA')
country.save() 
country = Country(title='Nauru', code='NR')
country.save() 
country = Country(title='Nepal', code='NP')
country.save() 
country = Country(title='Netherlands', code='NL')
country.save() 
country = Country(title='Netherlands Antilles', code='AN')
country.save() 
country = Country(title='New Caledonia', code='NC')
country.save() 
country = Country(title='New Zealand', code='NZ')
country.save() 
country = Country(title='Nicaragua', code='NI')
country.save() 
country = Country(title='Niger', code='NE')
country.save() 
country = Country(title='Nigeria', code='NG')
country.save() 
country = Country(title='Niue', code='NU')
country.save() 
country = Country(title='Norfolk Island', code='NF')
country.save() 
country = Country(title='Northern Mariana Islands', code='MP')
country.save() 
country = Country(title='Norway', code='NO')
country.save() 
country = Country(title='Oman', code='OM')
country.save() 
country = Country(title='Pakistan', code='PK')
country.save() 
country = Country(title='Palau', code='PW')
country.save() 
country = Country(title='Palestinian Territory, Occupied', code='PS')
country.save() 
country = Country(title='Panama', code='PA')
country.save() 
country = Country(title='Papua New Guinea', code='PG')
country.save() 
country = Country(title='Paraguay', code='PY')
country.save() 
country = Country(title='Peru', code='PE')
country.save() 
country = Country(title='Philippines', code='PH')
country.save() 
country = Country(title='Pitcairn', code='PN')
country.save() 
country = Country(title='Poland', code='PL')
country.save() 
country = Country(title='Portugal', code='PT')
country.save() 
country = Country(title='Puerto Rico', code='PR')
country.save() 
country = Country(title='Qatar', code='QA')
country.save() 
country = Country(title='Reunion', code='RE')
country.save() 
country = Country(title='Romania', code='RO')
country.save() 
country = Country(title='Russian Federation', code='RU')
country.save() 
country = Country(title='RWANDA', code='RW')
country.save() 
country = Country(title='Saint Helena', code='SH')
country.save() 
country = Country(title='Saint Kitts and Nevis', code='KN')
country.save() 
country = Country(title='Saint Lucia', code='LC')
country.save() 
country = Country(title='Saint Pierre and Miquelon', code='PM')
country.save() 
country = Country(title='Saint Vincent and the Grenadines', code='VC')
country.save() 
country = Country(title='Samoa', code='WS')
country.save() 
country = Country(title='San Marino', code='SM')
country.save() 
country = Country(title='Sao Tome and Principe', code='ST')
country.save() 
country = Country(title='Saudi Arabia', code='SA')
country.save() 
country = Country(title='Senegal', code='SN')
country.save() 
country = Country(title='Serbia and Montenegro', code='CS')
country.save() 
country = Country(title='Seychelles', code='SC')
country.save() 
country = Country(title='Sierra Leone', code='SL')
country.save() 
country = Country(title='Singapore', code='SG')
country.save() 
country = Country(title='Slovakia', code='SK')
country.save() 
country = Country(title='Slovenia', code='SI')
country.save() 
country = Country(title='Solomon Islands', code='SB')
country.save() 
country = Country(title='Somalia', code='SO')
country.save() 
country = Country(title='South Africa', code='ZA')
country.save() 
country = Country(title='South Georgia and the South Sandwich Islands', code='GS')
country.save() 
country = Country(title='Spain', code='ES')
country.save() 
country = Country(title='Sri Lanka', code='LK')
country.save() 
country = Country(title='Sudan', code='SD')
country.save() 
country = Country(title='Suriname', code='SR')
country.save() 
country = Country(title='Svalbard and Jan Mayen', code='SJ')
country.save() 
country = Country(title='Swaziland', code='SZ')
country.save() 
country = Country(title='Sweden', code='SE')
country.save() 
country = Country(title='Switzerland', code='CH')
country.save() 
country = Country(title='Syrian Arab Republic', code='SY')
country.save() 
country = Country(title='Taiwan, Province of China', code='TW')
country.save() 
country = Country(title='Tajikistan', code='TJ')
country.save() 
country = Country(title='Tanzania, United Republic of', code='TZ')
country.save() 
country = Country(title='Thailand', code='TH')
country.save() 
country = Country(title='Timor-Leste', code='TL')
country.save() 
country = Country(title='Togo', code='TG')
country.save() 
country = Country(title='Tokelau', code='TK')
country.save() 
country = Country(title='Tonga', code='TO')
country.save() 
country = Country(title='Trinidad and Tobago', code='TT')
country.save() 
country = Country(title='Tunisia', code='TN')
country.save() 
country = Country(title='Turkey', code='TR')
country.save() 
country = Country(title='Turkmenistan', code='TM')
country.save() 
country = Country(title='Turks and Caicos Islands', code='TC')
country.save() 
country = Country(title='Tuvalu', code='TV')
country.save() 
country = Country(title='Uganda', code='UG')
country.save() 
country = Country(title='Ukraine', code='UA')
country.save() 
country = Country(title='United Arab Emirates', code='AE')
country.save() 
country = Country(title='United Kingdom', code='GB')
country.save() 
country = Country(title='United States', code='US')
country.save() 
country = Country(title='United States Minor Outlying Islands', code='UM')
country.save() 
country = Country(title='Uruguay', code='UY')
country.save() 
country = Country(title='Uzbekistan', code='UZ')
country.save() 
country = Country(title='Vanuatu', code='VU')
country.save() 
country = Country(title='Venezuela', code='VE')
country.save() 
country = Country(title='Viet Nam', code='VN')
country.save() 
country = Country(title='Virgin Islands, British', code='VG')
country.save() 
country = Country(title='Virgin Islands, U.S.', code='VI')
country.save() 
country = Country(title='Wallis and Futuna', code='WF')
country.save() 
country = Country(title='Western Sahara', code='EH')
country.save() 
country = Country(title='Yemen', code='YE')
country.save() 
country = Country(title='Zambia', code='ZM')
country.save() 
country = Country(title='Zimbabwe', code='ZW') 